### ISSUE TITLE
Which transistors are used to drive the cathodes?

### ISSUE THREAD

**Issue by msurguy** [davidmpye/nixie-i2c#1]
Hi! 

It looks like that the requirements are not listing transistors used in the schematics, could you add them to the readme please?

**Comment by davidmpye** [comment]
Oops - they are MMBTA42s.

(e.g. http://uk.farnell.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=15001&langId=44&urlRequestType=Base&partNumber=1757937RL&storeId=10151)

I'll update readme.

Regards

David

**Comment by msurguy** [comment]
👍 thanks!

**Comment by davidmpye** [comment]
I'm working on a new version of nixie-i2c, which will actually use shift registers, and the boards will be chainable directly (so it'll be nixie-shift, or something ;-)

**Comment by msurguy** [comment]
@davidmpye That's great to hear! 

I will follow this project but meanwhile I will use Raspberry Pi Zero and Arduinix to control 6 nixie tubes. Really interested in cost efficient addressable single tube solution though, keep up the great work!

**Comment by msurguy** [comment]
PS @davidmpye if you haven't already, I highly suggest you put this project on Hackaday.io and let people like me easily follow your progress :)
